[project]
name = "mcp-on-cloudrun"
version = "0.1.0"
description = "Example of deploying a MCP server on Cloud Run"
requires-python = ">=3.10"
dependencies = [
    "fastmcp==2.6.1",
    "httpx>=0.27.0",
    "llama-cloud>=0.1.26",
    "llama-index>=0.12.43",
]
